import "./globals.css"
import { Inter, Jost } from "next/font/google"
import { ThemeProvider } from "./context/theme-provider"
import { PreventTransitions } from "./components/prevent-transitions"

// Optimize font loading with display swap and preload
const inter = Inter({ 
  subsets: ["latin"],
  display: 'swap',
  variable: "--font-inter",
  preload: true,
  fallback: ['system-ui', 'sans-serif']
})

const jost = Jost({
  subsets: ["latin"],
  display: 'swap',
  variable: "--font-jost",
  preload: true,
  fallback: ['system-ui', 'sans-serif']
})

export const metadata = {
  metadataBase: new URL('https://altesse-imena.vercel.app'),
  title: "Altesse Imena - Portfolio",
  description: "Personal portfolio of Altesse Imena, a software developer specializing in web applications and interactive experiences",
  keywords: ["software developer", "web development", "portfolio", "react", "next.js", "AstroTrip"],
  authors: [{ name: "Altesse Imena" }],
  robots: "index, follow",
  openGraph: {
    type: "website",
    title: "Altesse Imena - Portfolio",
    description: "Personal portfolio of Altesse Imena, a software developer specializing in web applications and interactive experiences",
    url: "https://altesse-imena.vercel.app",
    siteName: "Altesse Imena Portfolio",
    images: [
      {
        url: "/opengraph-image", // Dynamic OG image generated by Next.js
        width: 1200,
        height: 630,
        alt: "Altesse Imena - Software Developer Portfolio",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Altesse Imena - Portfolio",
    description: "Personal portfolio of Altesse Imena, a software developer specializing in web applications and interactive experiences",
    images: ["/opengraph-image"],
  },
}

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#0f172a" },
    { media: "(prefers-color-scheme: light)", color: "#ffffff" }
  ]
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} ${jost.variable} scroll-smooth`}>
      <head>
        <link rel="dns-prefetch" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body className="font-sans antialiased">
        <ThemeProvider defaultTheme="dark">
          <PreventTransitions />
          <div className="min-h-screen">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}

